version: '3.8'

services:
  sveltekit-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./default-rasa
        target: /default-rasa
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      # Variables adicionales que quieras sobrescribir