version: "3.8"

services:
  web:
    image: svelte
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - .env.docker
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
