version: '3.8'
services:
  prisma-migrate:
    container_name: svelte-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env.docker
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
